# Generated by Django 6.0 on 2026-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking'), ('CARD', 'Credit/Debit Card')], default='COD', max_length=20),
        ),
    ]
